# Generated by Django 4.0.4 on 2022-08-20 06:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('description2', models.TextField(blank=True, default=None, null=True)),
                ('description3', models.TextField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('url', models.URLField(max_length=300)),
                ('url2', models.URLField(max_length=300)),
                ('url3', models.URLField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picture6', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('picture1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('picture2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('picture3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('picture4', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('picture5', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
