# Generated by Django 4.0.4 on 2022-08-25 02:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theRest', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture4',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture5',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture6',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture6'),
        ),
    ]
