# Generated by Django 4.0.4 on 2022-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp500',
            name='cik',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
    ]
