# Generated by Django 4.0.4 on 2022-09-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0003_alter_sp500_cik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditie',
            name='exchange',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='commoditie',
            name='exchange_short',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='currency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='exchange',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='etf',
            name='exchange',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='etf',
            name='exchange_short',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nasdaq',
            name='founded',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sp500',
            name='date_first_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sp500',
            name='founded',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sp500',
            name='sector',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sp500',
            name='sub_sector',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
