# Generated by Django 4.0.4 on 2022-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0004_alter_commoditie_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp500',
            name='cik',
            field=models.IntegerField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
