# Generated by Django 4.0.4 on 2022-09-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0005_alter_sp500_cik'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasdaq',
            name='cik',
            field=models.IntegerField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
