# Generated by Django 4.0.4 on 2022-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0006_nasdaq_cik'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_featured',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
