# Generated by Django 4.0.4 on 2022-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0007_stock_stock_type_alter_stock_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchange_short',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
