# Generated by Django 4.0.4 on 2022-09-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0009_stock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexe',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
