# Generated by Django 4.0.4 on 2022-09-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0010_indexe_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexe',
            name='is_for_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
