# Generated by Django 4.0.4 on 2022-09-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0011_indexe_is_for_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('exchange', models.CharField(default='', max_length=300, null=True)),
            ],
        ),
    ]
