# Generated by Django 4.0.4 on 2022-10-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0015_balancesheet_cashflowstatement_incomestatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='interest_expense',
            field=models.IntegerField(blank=True, default=0, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='interest_income',
            field=models.IntegerField(blank=True, default=0, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='other_expenses',
            field=models.IntegerField(blank=True, default=0, max_length=400, null=True),
        ),
    ]
