# Generated by Django 4.0.4 on 2022-12-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0016_incomestatement_interest_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp500',
            name='date_first_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
