# Generated by Django 4.0.4 on 2022-12-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0017_alter_sp500_date_first_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='etf',
            name='universe',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
