# Generated by Django 4.0.4 on 2022-12-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0019_alter_crypto_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='profilestock',
            name='symbol',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='stock',
            name='owner_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
