# Generated by Django 4.0.4 on 2022-12-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0021_fundamentalattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentalattributes',
            name='average_inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fundamentalattributes',
            name='average_payables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fundamentalattributes',
            name='average_recievables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fundamentalattributes',
            name='net_debt_to_ebitda',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
