# Generated by Django 4.0.4 on 2022-12-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockuploader', '0023_profilestock_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestock',
            name='name',
        ),
    ]
