# Generated by Django 4.0.4 on 2022-10-01 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('category', models.CharField(choices=[('Quant', 'Quantitative'), ('Qualitative', 'Qualitative'), ('Risk', 'Risk'), ('Crypto', 'Crypto'), ('Fixed', 'Bonds'), ('Data Science', 'Datascience'), ('Programming', 'Programming'), ('Coding', 'Coding'), ('Python', 'Python'), ('Trading', 'Trading'), ('Macro Economic', 'Macro')], default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=None, max_length=300)),
                ('url', models.URLField(blank=True, default=None, max_length=300)),
                ('author', models.TextField()),
                ('image', models.URLField(blank=True, default=None, max_length=400, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
