# Generated by Django 4.0.4 on 2022-09-18 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commoditie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('currency', models.CharField(max_length=300)),
                ('exchange', models.CharField(default='', max_length=300)),
                ('exchange_short', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('currency', models.CharField(max_length=200)),
                ('exchange', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('exchange', models.CharField(default='', max_length=300)),
                ('exchange_short', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Indexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Nasdaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('sector', models.CharField(max_length=300)),
                ('sub_sector', models.CharField(max_length=300)),
                ('founded', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SP500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('sector', models.CharField(max_length=300)),
                ('sub_sector', models.CharField(max_length=300)),
                ('founded', models.CharField(max_length=300)),
                ('date_first_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('exchange', models.CharField(default='', max_length=300)),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('currency', models.CharField(max_length=300)),
                ('exchange', models.CharField(default=' ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fintank_screener.stock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
