# Generated by Django 4.0.4 on 2022-09-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintank_screener', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commoditie',
        ),
        migrations.DeleteModel(
            name='Crypto',
        ),
        migrations.DeleteModel(
            name='ETF',
        ),
        migrations.DeleteModel(
            name='Indexe',
        ),
        migrations.DeleteModel(
            name='Nasdaq',
        ),
        migrations.RemoveField(
            model_name='profilestock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='profilestock',
            name='user',
        ),
        migrations.DeleteModel(
            name='SP500',
        ),
        migrations.DeleteModel(
            name='TSX',
        ),
        migrations.DeleteModel(
            name='ProfileStock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
