# Generated by Django 4.0.4 on 2022-08-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_images_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image1',
            field=models.ImageField(null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image2',
            field=models.ImageField(null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image3',
            field=models.ImageField(null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='image1',
            field=models.ImageField(null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='image2',
            field=models.ImageField(null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='image3',
            field=models.ImageField(null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
