# Generated by Django 4.0.4 on 2022-08-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answer_image1_alter_answer_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='question_images/', verbose_name='Image'),
        ),
    ]
