# Generated by Django 4.0.4 on 2022-08-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_answer_image1_alter_answer_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Household', 'Household'), ('Music', 'Music'), ('Sales', 'Sales'), ('Education/Training', 'Education'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Retail', 'Retail'), ('Others', 'Others')], default='Technology', max_length=50),
        ),
    ]
