# Generated by Django 4.0.4 on 2022-08-20 17:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_picture1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture1',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture1'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture2',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture3',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture3'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture4',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture4'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture5',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture5'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture6',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture6'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_security_identifier',
            field=models.CharField(default=None, max_length=500, unique=True),
        ),
    ]
