# Generated by Django 4.0.4 on 2022-08-20 18:04

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about10',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about11',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about12',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about13',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about14',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about4',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about5',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about6',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about7',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about8',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about9',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='document',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='document1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='document2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='document3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='document4',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture10',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture11',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture12',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture4',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture5',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture6',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture7',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture8',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture9',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_account_id',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('company_number', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('company_email', models.EmailField(blank=True, default=None, max_length=300, null=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.CharField(max_length=700, null=True)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('about1', models.TextField(blank=True, default=None, null=True)),
                ('about2', models.TextField(blank=True, default=None, null=True)),
                ('about3', models.TextField(blank=True, default=None, null=True)),
                ('about4', models.TextField(blank=True, default=None, null=True)),
                ('about5', models.TextField(blank=True, default=None, null=True)),
                ('about6', models.TextField(blank=True, default=None, null=True)),
                ('about7', models.TextField(blank=True, default=None, null=True)),
                ('about8', models.TextField(blank=True, default=None, null=True)),
                ('about9', models.TextField(blank=True, default=None, null=True)),
                ('about10', models.TextField(blank=True, default=None, null=True)),
                ('about11', models.TextField(blank=True, default=None, null=True)),
                ('about12', models.TextField(blank=True, default=None, null=True)),
                ('about13', models.TextField(blank=True, default=None, null=True)),
                ('about14', models.TextField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('cover_picture', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('profile_picture6', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture6')),
                ('profile_picture1', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture1')),
                ('profile_picture2', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture2')),
                ('profile_picture3', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture3')),
                ('profile_picture4', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture4')),
                ('profile_picture5', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='profile_picture5')),
                ('profile_picture7', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('profile_picture8', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('profile_picture9', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('profile_picture11', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('profile_picture12', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('profile_picture10', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('document1', models.FileField(blank=True, null=True, upload_to='')),
                ('document2', models.FileField(blank=True, null=True, upload_to='')),
                ('document3', models.FileField(blank=True, null=True, upload_to='')),
                ('document4', models.FileField(blank=True, null=True, upload_to='')),
                ('stripe_account_id', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
