# Generated by Django 4.0.4 on 2022-09-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_cs',
            field=models.URLField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
