# Generated by Django 4.0.4 on 2022-09-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_profile_picture_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture_cs',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
