# Generated by Django 4.0.4 on 2022-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_profile_picture_cs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document1',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture1',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture10',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture12',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture2',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture3',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture4',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture5',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture6',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture7',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture8',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
