# Generated by Django 4.0.4 on 2022-09-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_picture1_alter_product_picture2_and_more'),
        ('users', '0013_alter_userprofile_cover_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='store_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document2',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document3',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document4',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture11',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture9',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
