# Generated by Django 4.0.4 on 2022-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_userprofile_store_name_userprofile_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='store',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Subscriber', 'Subscriber'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Employee', 'Employee'), ('Client', 'Client')], default='Subscriber', max_length=300),
        ),
    ]
