# Generated by Django 4.0.4 on 2022-08-26 04:46

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('section_one', models.TextField(null=True)),
                ('section_two', models.TextField(null=True)),
                ('section_three', models.TextField(blank=True, null=True)),
                ('section_four', models.TextField(blank=True, null=True)),
                ('section_five', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.CharField(max_length=700, null=True)),
                ('jobType', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Temporary'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer')], default='Permanent', max_length=50)),
                ('education', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd'), ('Certificate', 'Certificate')], default='Bachelors', max_length=50)),
                ('industry_detail', models.TextField(null=True)),
                ('industry', models.CharField(choices=[('Business', 'Business'), ('Information Technology', 'It'), ('Banking', 'Banking'), ('Marketing', 'Marketing'), ('Energy', 'Energy'), ('Sales', 'Sales'), ('Education/Training', 'Education'), ('Telecommunication', 'Telecommunication'), ('Retail', 'Retail'), ('Others', 'Others')], default='Business', max_length=50)),
                ('education_detail', models.TextField(null=True)),
                ('experience', models.CharField(choices=[('No Experience', 'No Experience'), ('1 Years', 'One Year'), ('2 Years', 'Two Year'), ('3 Years above', 'Three Year Plus')], default='No Experience', max_length=50)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('positions', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(default='none', max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('applicationExpiry', models.DateTimeField(default=jobs.models.return_date_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(max_length=200)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
