# Generated by Django 4.0.4 on 2022-08-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
