# Generated by Django 4.0.4 on 2022-07-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_education_detail_job_industry_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='section_five',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='section_four',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='section_three',
            field=models.TextField(blank=True, null=True),
        ),
    ]
