# Generated by Django 4.0.4 on 2022-08-25 14:24

import cloudinary.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('description2', models.TextField(blank=True, default=None, null=True)),
                ('picture1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture1')),
                ('picture2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture2')),
                ('picture3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture3')),
                ('picture4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture4')),
                ('picture5', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture5')),
                ('picture6', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture6')),
                ('picture7', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture7')),
                ('count', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('unique_identifier', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('description2', models.TextField(blank=True, default=None, null=True)),
                ('description3', models.TextField(blank=True, default=None, null=True)),
                ('picture1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture1')),
                ('picture2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='picture2')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=300)),
                ('unique_identifier', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(choices=[('Canada', 'Canada'), ('US', 'Us')], default='Canada', max_length=60)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('employees', models.ManyToManyField(null=True, related_name='store_employee', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
