# Generated by Django 4.0.4 on 2022-08-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
