# Generated by Django 4.0.4 on 2022-12-30 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_alter_product_picture1_alter_product_picture2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(related_name='store_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
